name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Stack and Cabal
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          ~/.local/bin
        key: ${{ runner.os }}-build-${{ hashFiles('blog-project/**/*.cabal') }}-${{ hashFiles('blog-project/stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Stack (if needed)
      run: |
        if ! command -v stack &> /dev/null; then
          curl -sSL https://get.haskellstack.org/ | sh
        fi

    - name: Check Stack Version
      run: stack --version
      working-directory: blog-project

    - name: Verify Project Structure
      run: |
        ls -al
        cat stack.yaml
      working-directory: blog-project

    - name: Install dependencies
      run: stack setup && stack build --only-dependencies
      working-directory: blog-project

    - name: Build
      run: stack build
      working-directory: blog-project

    - name: Run tests
      run: stack test
      working-directory: blog-project
